### ISSUE TITLE
UnboundLocalError: local variable 'Ci_' referenced before assignment

### ISSUE THREAD

**Issue by JustinLoye** [COSIN3-UOC/nestedness_modularity_in-block_nestedness_analysis#1]
This error occurs when I attempt to run structural_analysis.py, line 55.

Comparing the "# In-block nestedness with B=1" block of code with the "#Modularity Extremal" and "# Inblock nestedness extremal" blocks, I guess the fix is replacing  
```python
max_blockN=max(max(Ci_[0]),max(Ci_[1]))+1
```
by  
```python
max_blockN=max(max(Cn_[0]),max(Cn_[1]))+1
```

PR: #2

**Comment by mariapalazzi** [comment]
correct! Thanks
